kind: Namespace
apiVersion: v1
metadata:
  name: monitoring
---
kind: HelmRepository
apiVersion: source.toolkit.fluxcd.io/v1
metadata: 
  name: prometheus
  namespace: monitoring
spec:
  interval: 6h
  url: https://kubeslice.aveshalabs.io/repository/kubeslice-helm-ent-prod/ 
---
kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 6h
  releaseName: prometheus
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: kubeslice/prometheus
      interval: 6h
      sourceRef:
        kind: HelmRepository
        name: prometheus