kind: Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
metadata:
  name: boutique
  namespace: flux-system
spec:
  path: "./apps/development/boutique"
  interval: 1m
  prune: true
  targetNamespace: online-boutique
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system