kind: Gateway
apiVersion: networking.istio.io/v1
metadata:
  name: frontend-gateway
  namespace: online-boutique
spec:
  selector:
    istio: ingress # Debe coincidir con la etiqueta asignada al pod istio-ingress
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*" # "*" debe ser reemplazado con el hostname apropiado para mayor seguridad
---
kind: VirtualService
apiVersion: networking.istio.io/v1
metadata:
  name: frontend-virtual-service
  namespace: online-boutique
spec:
  hosts:
    - "*" # Debe ser igual al definido en el gateway
  gateways:
    - frontend-gateway
  http:
    - route: 
      - destination: # Sin matchers, usando la ruta default. Ref. https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPMatchRequest
          host: frontend # Istio transforma este valor en el FQDN del servicio
          port:
            number: 80