kind: Namespace
apiVersion: v1
metadata:
  name: istio-system
---
kind: HelmRepository
apiVersion: helm.toolkit.fluxcd.io/v2
metadata:
  name: istio
  namespace: istio-system
spec:
  interval: 6h
  url: https://kubeslice.aveshalabs.io/repository/kubeslice-helm-ent-prod/ 
---
kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 6h
  releaseName: istio-base
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: istio-base
      interval: 6h
      sourceRef:
        kind: HelmRepository
        name: istio
---
kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 6h
  releaseName: istiod
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec: 
      chart: istio-discovery
      interval: 6h
      sourceRef:
        kind: HelmRepository
        name: istio